spring.application.name=WEBSOCKET

# H2 database opsætning
spring.datasource.url=jdbc:h2:mem:moviecatalog
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true

spring.datasource.username=sa
spring.datasource.password=

# H2 konsol - så du kan se databasen i browseren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console