// Food Delivery Order Service
// Handles order status and real time tracking

syntax = "proto3";

package order;


option java_package = "order";
option java_multiple_files = true;


enum OrderStatus {
  PENDING = 0;
  SHIPPED = 1;
  DELIVERED = 2;
  CANCELLED = 3;
}

// Defining data structures for order status and tracking
message GetOrderStatusRequest {
  string order_id = 1;
}

message GetOrderStatusResponse {
  string order_id = 1;
  string order_status = 2;
  string message = 3;
}

message TrackOrderRequest {
  string order_id = 1;
}

message TrackOrderResponse {
  string order_id = 1;
  string order_status = 2;
  string location = 3;
}

// Defining API methods for order service

service OrderService {
  rpc GetOrderStatus (GetOrderStatusRequest) returns (GetOrderStatusResponse);
  rpc TrackOrder (stream TrackOrderRequest) returns (stream TrackOrderResponse);
}