[tool.poetry]
name = "Exam-Project"
version = "0.1.0"
description = "FastAPI Rest project"
authors = ["Benjamin Harris <beha1503@gmail.com>"]
license = ""
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = { extras = ["standard"], version = "^0.32.0" }
PyJWT = "^2.8"
bcrypt = "^4.0"
aiosqlite = "^0.20"
redis = "^5"
pydantic-settings = "^2.0"
python-multipart = ">=0.0.5"
email-validator = ">=2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
pytest-asyncio = "^0.23"
httpx = "^0.27"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
